table prod_data
	lineageTag: c881a85e-6433-49df-b869-2ccc8f90fb8f

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 9b769f29-e218-48ad-ae40-64c1cd1cd362
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Quality Index'
		dataType: string
		lineageTag: 174aa07a-aace-447d-aa51-ec564be79592
		summarizeBy: none
		sourceColumn: Quality Index
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Apple7
		dataType: string
		lineageTag: 061e0d97-686c-4876-9f0e-6f4eaeb1a3e2
		summarizeBy: none
		sourceColumn: Apple7

		annotation SummarizationSetBy = Automatic

	column Apple4
		dataType: string
		lineageTag: 8d1c1110-73dc-4f88-bc0a-f59d0e6870c5
		summarizeBy: none
		sourceColumn: Apple4

		annotation SummarizationSetBy = Automatic

	column Apple1
		dataType: string
		lineageTag: 5e0ab23e-3807-4295-86a6-6f0e3fa912c6
		summarizeBy: none
		sourceColumn: Apple1

		annotation SummarizationSetBy = Automatic

	column Apple2
		dataType: string
		lineageTag: f22a9f68-636e-4384-8c95-5610373dd0c5
		summarizeBy: none
		sourceColumn: Apple2

		annotation SummarizationSetBy = Automatic

	column Apple3
		dataType: string
		lineageTag: fa85c8c3-45ca-47ad-b8bb-4952ad5ea49c
		summarizeBy: none
		sourceColumn: Apple3

		annotation SummarizationSetBy = Automatic

	column Apple6
		dataType: string
		lineageTag: 63b9df16-a25a-4810-97a0-b1d9c7bf391b
		summarizeBy: none
		sourceColumn: Apple6

		annotation SummarizationSetBy = Automatic

	column Apple5
		dataType: string
		lineageTag: 3564f096-897f-4246-8ddd-2f30d98c3f3c
		summarizeBy: none
		sourceColumn: Apple5

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: double
		lineageTag: 23f6abcb-e45f-4ed4-81ba-4d8e8fb4ae16
		summarizeBy: sum
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Update'
		dataType: string
		lineageTag: f811570c-6c82-4797-8d46-e6b3adb533ba
		summarizeBy: none
		sourceColumn: Date Update

		annotation SummarizationSetBy = Automatic

	partition prod_data = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rosal\Repositories\GitHub\handbooks\data-analysis-handbook\data-visualization\power-bi\examples\sorting-tables\data\prod_data3.xlsx"), null, true),
				    Sheet1_Sheet = Origen{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Added Index" = Table.AddIndexColumn(#"Promoted Headers", "Index", 0, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Quality Index", "Apple1", "Apple2", "Apple3", "Apple4", "Apple5", "Apple6", "Apple7", "Percentage", "Date Update"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"Date Update", type date}, {"Percentage", Percentage.Type}}),
				    #"Run Python script" = Python.Execute("# Run in Power Query#(lf)import pandas as pd#(lf)#(lf)# Get the row where Quality Index == 'Count'#(lf)count_row = dataset[dataset['Quality Index'] == 'Count'].iloc[0]#(lf)#(lf)# Find all Apple columns#(lf)apple_cols = [col for col in dataset.columns if col.startswith('Apple')]#(lf)#(lf)# Create a dictionary of column names and their count values#(lf)count_dict = {col: int(count_row[col]) for col in apple_cols}#(lf)#(lf)# Sort Apple columns by count (descending)#(lf)sorted_apple_cols = sorted(count_dict.keys(), key=lambda x: count_dict[x], reverse=True)#(lf)#(lf)# Reorder all columns: keep Index and Quality Index first, #(lf)# then sorted Apple columns, then the rest#(lf)other_cols = [col for col in dataset.columns #(lf)              if col not in apple_cols and col not in ['Index', 'Quality Index']]#(lf)#(lf)new_column_order = ['Quality Index'] + sorted_apple_cols + other_cols#(lf)#(lf)# Reorder the dataframe#(lf)dataset = dataset[new_column_order]# 'dataset' holds the input data for this script#(lf)",[dataset=#"Changed Type"]),
				    dataset = #"Run Python script"{[Name="dataset"]}[Value],
				    #"Changed Type1" = Table.TransformColumnTypes(dataset,{{"Quality Index", type text}, {"Apple7", type text}, {"Apple4", type text}, {"Apple1", type text}, {"Apple2", type text}, {"Apple3", type text}, {"Apple6", type text}, {"Apple5", type text}, {"Percentage", type number}, {"Date Update", type text}}),
				    #"Added Index1" = Table.AddIndexColumn(#"Changed Type1", "Index", 0, 1, Int64.Type),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Index1",{"Index", "Quality Index", "Apple7", "Apple4", "Apple1", "Apple2", "Apple3", "Apple6", "Apple5", "Percentage", "Date Update"})
				in
				    #"Reordered Columns1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

